services:
  - type: web
    name: travel-planner-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AMAP_KEY
        value: f68420453037ba3962f3a132a5879099
      - key: AMAP_SECRET
        value: 001e797bdecd038ccf176c0ecfb0871a
      - key: JUHE_API_KEY
        value: 69664bd3678547f37844d3a614c8d8e9
