"""
全国城市基础数据 - 包含所有地级市
"""

ALL_CITIES_BASIC = {
    # 河北省
    "石家庄": {"province": "河北", "highlights": "正定古城、赵州桥", "type": "历史文化"},
    "唐山": {"province": "河北", "highlights": "清东陵、月坨岛", "type": "海滨度假"},
    "秦皇岛": {"province": "河北", "highlights": "山海关、北戴河、阿那亚", "type": "海滨度假"},
    "邯郸": {"province": "河北", "highlights": "赵城、娲皇宫", "type": "历史文化"},
    "邢台": {"province": "河北", "highlights": "崆山白云洞、邢台峡谷群", "type": "自然风光"},
    "保定": {"province": "河北", "highlights": "白洋淀、野三坡、直隶总督署", "type": "历史文化"},
    "张家口": {"province": "河北", "highlights": "坝上草原、崇礼滑雪场", "type": "自然风光"},
    "承德": {"province": "河北", "highlights": "避暑山庄、外八庙、木兰围场", "type": "历史文化"},
    "沧州": {"province": "河北", "highlights": "吴桥杂技大世界", "type": "文化体验"},
    "廊坊": {"province": "河北", "highlights": "天下第一城", "type": "历史文化"},
    "衡水": {"province": "河北", "highlights": "衡水湖、武强年画博物馆", "type": "自然风光"},
    
    # 山西省
    "太原": {"province": "山西", "highlights": "晋祠、双塔", "type": "历史文化"},
    "大同": {"province": "山西", "highlights": "云冈石窟、悬空寺、古城墙", "type": "历史文化"},
    "阳泉": {"province": "山西", "highlights": "娘子关、藏山", "type": "历史文化"},
    "长治": {"province": "山西", "highlights": "太行山大峡谷、平遥古城", "type": "自然风光"},
    "晋城": {"province": "山西", "highlights": "皇城相府、王莽岭", "type": "历史文化"},
    "朔州": {"province": "山西", "highlights": "应县木塔、崇福寺", "type": "历史文化"},
    "晋中": {"province": "山西", "highlights": "平遥古城、乔家大院", "type": "历史文化"},
    "运城": {"province": "山西", "highlights": "关帝庙、永乐宫、盐湖", "type": "历史文化"},
    "忻州": {"province": "山西", "highlights": "五台山、雁门关", "type": "宗教文化"},
    "临汾": {"province": "山西", "highlights": "壶口瀑布、洪洞大槐树", "type": "自然风光"},
    "吕梁": {"province": "山西", "highlights": "碛口古镇、北武当山", "type": "历史文化"},
    
    # 辽宁省
    "沈阳": {"province": "辽宁", "highlights": "故宫、张氏帅府", "type": "历史文化"},
    "大连": {"province": "辽宁", "highlights": "星海广场、发现王国、金石滩", "type": "海滨度假"},
    "鞍山": {"province": "辽宁", "highlights": "千山、玉佛苑", "type": "自然风光"},
    "抚顺": {"province": "辽宁", "highlights": "赫图阿拉城、雷锋纪念馆", "type": "历史文化"},
    "本溪": {"province": "辽宁", "highlights": "本溪水洞、关门山", "type": "自然风光"},
    "丹东": {"province": "辽宁", "highlights": "鸭绿江、凤凰山", "type": "边境旅游"},
    "锦州": {"province": "辽宁", "highlights": "笔架山、辽沈战役纪念馆", "type": "历史文化"},
    "营口": {"province": "辽宁", "highlights": "鲅鱼圈、熊岳温泉", "type": "海滨度假"},
    "阜新": {"province": "辽宁", "highlights": "海棠山、瑞应寺", "type": "自然风光"},
    "辽阳": {"province": "辽宁", "highlights": "广佑寺、太子河", "type": "历史文化"},
    "盘锦": {"province": "辽宁", "highlights": "红海滩", "type": "自然风光"},
    "铁岭": {"province": "辽宁", "highlights": "龙首山、调兵山", "type": "自然风光"},
    "朝阳": {"province": "辽宁", "highlights": "鸟化石地质公园", "type": "自然风光"},
    "葫芦岛": {"province": "辽宁", "highlights": "兴城古城、九门口长城", "type": "历史文化"},
    
    # 吉林省
    "长春": {"province": "吉林", "highlights": "伪满皇宫、净月潭、长影", "type": "历史文化"},
    "吉林": {"province": "吉林", "highlights": "雾凇岛、北山、松花湖", "type": "自然风光"},
    "四平": {"province": "吉林", "highlights": "叶赫那拉古城", "type": "历史文化"},
    "辽阳": {"province": "辽宁", "highlights": "龙顶山", "type": "自然风光"},
    "通化": {"province": "吉林", "highlights": "高句丽遗址、龙湾群", "type": "历史文化"},
    "白山": {"province": "吉林", "highlights": "长白山南坡", "type": "自然风光"},
    "松原": {"province": "吉林", "highlights": "查干湖", "type": "自然风光"},
    "白城": {"province": "吉林", "highlights": "向海湿地", "type": "自然风光"},
    "延边": {"province": "吉林", "highlights": "长白山、朝鲜族风情", "type": "边境旅游"},
    
    # 黑龙江省
    "哈尔滨": {"province": "黑龙江", "highlights": "冰雪大世界、中央大街、索菲亚", "type": "冰雪旅游"},
    "齐齐哈尔": {"province": "黑龙江", "highlights": "扎龙湿地", "type": "自然风光"},
    "鸡西": {"province": "黑龙江", "highlights": "兴凯湖", "type": "边境旅游"},
    "鹤岗": {"province": "黑龙江", "highlights": "名山岛", "type": "自然风光"},
    "双鸭山": {"province": "黑龙江", "highlights": "七星峰", "type": "自然风光"},
    "大庆": {"province": "黑龙江", "highlights": "铁人纪念馆", "type": "工业旅游"},
    "伊春": {"province": "黑龙江", "highlights": "林海奇石、茅兰沟", "type": "自然风光"},
    "佳木斯": {"province": "黑龙江", "highlights": "黑瞎子岛", "type": "边境旅游"},
    "七台河": {"province": "黑龙江", "highlights": "桃山水库", "type": "自然风光"},
    "牡丹江": {"province": "黑龙江", "highlights": "镜泊湖、雪乡", "type": "自然风光"},
    "黑河": {"province": "黑龙江", "highlights": "五大连池、瑷珲古城", "type": "边境旅游"},
    "绥化": {"province": "黑龙江", "highlights": "金龟山庄", "type": "自然风光"},
    "大兴安岭": {"province": "黑龙江", "highlights": "北极村、北红村", "type": "边境旅游"},
    
    # 江苏省
    "南京": {"province": "江苏", "highlights": "中山陵、夫子庙、明孝陵", "type": "历史文化"},
    "无锡": {"province": "江苏", "highlights": "灵山大佛、鼋头渚、惠山", "type": "历史文化"},
    "徐州": {"province": "江苏", "highlights": "云龙湖、汉墓", "type": "历史文化"},
    "常州": {"province": "江苏", "highlights": "恐龙园、天目湖", "type": "主题乐园"},
    "苏州": {"province": "江苏", "highlights": "拙政园、周庄、虎丘", "type": "历史文化"},
    "南通": {"province": "江苏", "highlights": "濠河、狼山", "type": "历史文化"},
    "连云港": {"province": "江苏", "highlights": "花果山、渔湾", "type": "自然风光"},
    "淮安": {"province": "江苏", "highlights": "周恩来故里、洪泽湖", "type": "历史文化"},
    "盐城": {"province": "江苏", "highlights": "麋鹿保护区、荷兰花海", "type": "自然风光"},
    "扬州": {"province": "江苏", "highlights": "瘦西湖、个园", "type": "历史文化"},
    "镇江": {"province": "江苏", "highlights": "金山寺、北固山", "type": "历史文化"},
    "泰州": {"province": "江苏", "highlights": "溱湖湿地", "type": "自然风光"},
    "宿迁": {"province": "江苏", "highlights": "洪泽湖湿地、项王故里", "type": "历史文化"},
    
    # 浙江省
    "杭州": {"province": "浙江", "highlights": "西湖、灵隐寺、千岛湖", "type": "历史文化"},
    "宁波": {"province": "浙江", "highlights": "天一阁、普陀山", "type": "历史文化"},
    "温州": {"province": "浙江", "highlights": "雁荡山、楠溪江", "type": "自然风光"},
    "嘉兴": {"province": "浙江", "highlights": "西塘、乌镇、南湖", "type": "历史文化"},
    "湖州": {"province": "浙江", "highlights": "莫干山、南浔", "type": "自然风光"},
    "绍兴": {"province": "浙江", "highlights": "鲁迅故里、柯岩", "type": "历史文化"},
    "金华": {"province": "浙江", "highlights": "横店影视城、义乌", "type": "主题乐园"},
    "衢州": {"province": "浙江", "highlights": "江郎山、廿八都", "type": "自然风光"},
    "舟山": {"province": "浙江", "highlights": "普陀山、朱家尖", "type": "海滨度假"},
    "台州": {"province": "浙江", "highlights": "神仙居、临海古城", "type": "自然风光"},
    "丽水": {"province": "浙江", "highlights": "仙都、云和梯田", "type": "自然风光"},
    
    # 安徽省
    "合肥": {"province": "安徽", "highlights": "包公祠、三河古镇", "type": "历史文化"},
    "芜湖": {"province": "安徽", "highlights": "方特、鸠兹古镇", "type": "主题乐园"},
    "蚌埠": {"province": "安徽", "highlights": "龙子湖、花鼓灯", "type": "自然风光"},
    "淮南": {"province": "安徽", "highlights": "八公山", "type": "历史文化"},
    "马鞍山": {"province": "安徽", "highlights": "采石矶", "type": "自然风光"},
    "淮北": {"province": "安徽", "highlights": "相山公园", "type": "自然风光"},
    "铜陵": {"province": "安徽", "highlights": "天井湖", "type": "自然风光"},
    "安庆": {"province": "安徽", "highlights": "天柱山、迎江寺", "type": "自然风光"},
    "黄山": {"province": "安徽", "highlights": "黄山、宏村、西递", "type": "自然风光"},
    "滁州": {"province": "安徽", "highlights": "琅琊山", "type": "历史文化"},
    "阜阳": {"province": "安徽", "highlights": "八里河", "type": "自然风光"},
    "宿州": {"province": "安徽", "highlights": "皇藏峪、虞姬墓", "type": "历史文化"},
    "六安": {"province": "安徽", "highlights": "天堂寨、大别山", "type": "自然风光"},
    "亳州": {"province": "安徽", "highlights": "曹操运兵道、花戏楼", "type": "历史文化"},
    "池州": {"province": "安徽", "highlights": "九华山", "type": "宗教文化"},
    "宣城": {"province": "安徽", "highlights": "敬亭山、桃花潭", "type": "自然风光"},
    
    # 福建省
    "福州": {"province": "福建", "highlights": "三坊七巷、鼓山", "type": "历史文化"},
    "厦门": {"province": "福建", "highlights": "鼓浪屿、南普陀、环岛路", "type": "海滨度假"},
    "莆田": {"province": "福建", "highlights": "湄洲岛、广化寺", "type": "宗教文化"},
    "三明": {"province": "福建", "highlights": "泰宁大金湖、白水洋", "type": "自然风光"},
    "泉州": {"province": "福建", "highlights": "开元寺、清源山、蟳埔村", "type": "历史文化"},
    "漳州": {"province": "福建", "highlights": "云水谣、火山岛", "type": "自然风光"},
    "南平": {"province": "福建", "highlights": "武夷山、下梅古村", "type": "自然风光"},
    "龙岩": {"province": "福建", "highlights": "鼓浪屿？不，龙岩有土楼", "type": "历史文化"},
    "宁德": {"province": "福建", "highlights": "太姥山、嵛山岛", "type": "自然风光"},
    
    # 江西省
    "南昌": {"province": "江西", "highlights": "滕王阁、八一广场", "type": "历史文化"},
    "景德镇": {"province": "江西", "highlights": "古窑、陶瓷博物馆", "type": "文化体验"},
    "萍乡": {"province": "江西", "highlights": "武功山", "type": "自然风光"},
    "九江": {"province": "江西", "highlights": "庐山、鄱阳湖", "type": "自然风光"},
    "新余": {"province": "江西", "highlights": "仙女湖", "type": "自然风光"},
    "鹰潭": {"province": "江西", "highlights": "龙虎山", "type": "自然风光"},
    "赣州": {"province": "江西", "highlights": "通天岩、客家围屋", "type": "历史文化"},
    "吉安": {"province": "江西", "highlights": "井冈山、武功山", "type": "红色旅游"},
    "宜春": {"province": "江西", "highlights": "明月山、温汤温泉", "type": "自然风光"},
    "抚州": {"province": "江西", "highlights": "梦湖、流坑古村", "type": "历史文化"},
    "上饶": {"province": "江西", "highlights": "三清山、婺源、鄱阳湖", "type": "自然风光"},
    
    # 山东省
    "济南": {"province": "山东", "highlights": "趵突泉、大明湖、千佛山", "type": "历史文化"},
    "青岛": {"province": "山东", "highlights": "栈桥、八大关、崂山", "type": "海滨度假"},
    "淄博": {"province": "山东", "highlights": "周村古商城、聊斋园", "type": "历史文化"},
    "枣庄": {"province": "山东", "highlights": "台儿庄古城、微山湖", "type": "历史文化"},
    "东营": {"province": "山东", "highlights": "黄河入海口", "type": "自然风光"},
    "烟台": {"province": "山东", "highlights": "蓬莱阁、养马岛", "type": "海滨度假"},
    "潍坊": {"province": "山东", "highlights": "风筝博物馆、青州古城", "type": "历史文化"},
    "济宁": {"province": "山东", "highlights": "三孔、微山湖", "type": "历史文化"},
    "泰安": {"province": "山东", "highlights": "泰山、岱庙", "type": "自然风光"},
    "威海": {"province": "山东", "highlights": "刘公岛、成山头", "type": "海滨度假"},
    "日照": {"province": "山东", "highlights": "万平口、五莲山", "type": "海滨度假"},
    "临沂": {"province": "山东", "highlights": "蒙山、王羲之故居", "type": "历史文化"},
    "德州": {"province": "山东", "highlights": "苏禄王墓、太阳谷", "type": "历史文化"},
    "聊城": {"province": "山东", "highlights": "东昌湖、光岳楼", "type": "历史文化"},
    "滨州": {"province": "山东", "highlights": "孙武园", "type": "历史文化"},
    "菏泽": {"province": "山东", "highlights": "曹州牡丹园", "type": "自然风光"},
    
    # 河南省
    "郑州": {"province": "河南", "highlights": "少林寺、龙门石窟", "type": "历史文化"},
    "开封": {"province": "河南", "highlights": "清明上河园、大相国寺、铁塔", "type": "历史文化"},
    "洛阳": {"province": "河南", "highlights": "龙门石窟、白马寺、老君山", "type": "历史文化"},
    "平顶山": {"province": "河南", "highlights": "尧山、中原大佛", "type": "自然风光"},
    "安阳": {"province": "河南", "highlights": "殷墟、红旗渠", "type": "历史文化"},
    "鹤壁": {"province": "河南", "highlights": "浚县古城", "type": "历史文化"},
    "新乡": {"province": "河南", "highlights": "万仙山、八里沟", "type": "自然风光"},
    "焦作": {"province": "河南", "highlights": "云台山、神农山", "type": "自然风光"},
    "濮阳": {"province": "河南", "highlights": "戚城文物景区", "type": "历史文化"},
    "许昌": {"province": "河南", "highlights": "三国文化产业园", "type": "历史文化"},
    "漯河": {"province": "河南", "highlights": "南街村", "type": "红色旅游"},
    "三门峡": {"province": "河南", "highlights": "天鹅湖、地坑院", "type": "自然风光"},
    "南阳": {"province": "河南", "highlights": "武侯祠、西峡恐龙园", "type": "历史文化"},
    "商丘": {"province": "河南", "highlights": "古城墙、芒砀山", "type": "历史文化"},
    "信阳": {"province": "河南", "highlights": "鸡公山、南湾湖", "type": "自然风光"},
    "周口": {"province": "河南", "highlights": "太昊陵、老子故里", "type": "历史文化"},
    "驻马店": {"province": "河南", "highlights": "嵖岈山、南海禅寺", "type": "自然风光"},
    "济源": {"province": "河南", "highlights": "王屋山", "type": "自然风光"},
    
    # 湖北省
    "武汉": {"province": "湖北", "highlights": "黄鹤楼、东湖、户部巷", "type": "历史文化"},
    "黄石": {"province": "湖北", "highlights": "仙岛湖、东方山", "type": "自然风光"},
    "十堰": {"province": "湖北", "highlights": "武当山、神农架", "type": "自然风光"},
    "宜昌": {"province": "湖北", "highlights": "三峡大坝、三峡人家", "type": "自然风光"},
    "襄阳": {"province": "湖北", "highlights": "古隆中、古城墙", "type": "历史文化"},
    "鄂州": {"province": "湖北", "highlights": "莲花山", "type": "自然风光"},
    "荆门": {"province": "湖北", "highlights": "明显陵、漳河", "type": "历史文化"},
    "孝感": {"province": "湖北", "highlights": "双峰山、董永公园", "type": "自然风光"},
    "荆州": {"province": "湖北", "highlights": "荆州古城、楚王车马阵", "type": "历史文化"},
    "黄冈": {"province": "湖北", "highlights": "东坡赤壁、天堂寨", "type": "历史文化"},
    "咸宁": {"province": "湖北", "highlights": "九宫山、温泉谷", "type": "自然风光"},
    "随州": {"province": "湖北", "highlights": "炎帝神农故里", "type": "历史文化"},
    "恩施": {"province": "湖北", "highlights": "大峡谷、腾龙洞", "type": "自然风光"},
    
    # 湖南省
    "长沙": {"province": "湖南", "highlights": "岳麓山、橘子洲、湖南省博", "type": "历史文化"},
    "株洲": {"province": "湖南", "highlights": "炎帝陵、方特", "type": "主题乐园"},
    "湘潭": {"province": "湖南", "highlights": "韶山、彭德怀故居", "type": "红色旅游"},
    "衡阳": {"province": "湖南", "highlights": "衡山、石鼓书院", "type": "自然风光"},
    "邵阳": {"province": "湖南", "highlights": "崀山、南山牧场", "type": "自然风光"},
    "岳阳": {"province": "湖南", "highlights": "岳阳楼、君山岛", "type": "历史文化"},
    "常德": {"province": "湖南", "highlights": "桃花源、武陵源", "type": "自然风光"},
    "张家界": {"province": "湖南", "highlights": "天门山、武陵源、玻璃桥", "type": "自然风光"},
    "益阳": {"province": "湖南", "highlights": "桃花江竹海", "type": "自然风光"},
    "郴州": {"province": "湖南", "highlights": "东江湖、莽山", "type": "自然风光"},
    "永州": {"province": "湖南", "highlights": "九疑山、阳明山", "type": "自然风光"},
    "怀化": {"province": "湖南", "highlights": "芷江受降纪念坊", "type": "红色旅游"},
    "娄底": {"province": "湖南", "highlights": "梅山龙宫、大熊山", "type": "自然风光"},
    "湘西": {"province": "湖南", "highlights": "凤凰古城、张家界", "type": "历史文化"},
    
    # 广东省
    "广州": {"province": "广东", "highlights": "陈家祠、白云山、长隆", "type": "历史文化"},
    "韶关": {"province": "广东", "highlights": "丹霞山、南华寺", "type": "自然风光"},
    "深圳": {"province": "广东", "highlights": "世界之窗、欢乐谷、大梅沙", "type": "主题乐园"},
    "珠海": {"province": "广东", "highlights": "长隆海洋王国、情侣路", "type": "海滨度假"},
    "汕头": {"province": "广东", "highlights": "南澳岛、小公园", "type": "海滨度假"},
    "佛山": {"province": "广东", "highlights": "祖庙、西樵山", "type": "历史文化"},
    "江门": {"province": "广东", "highlights": "碉楼、台山上川岛", "type": "历史文化"},
    "湛江": {"province": "广东", "highlights": "雷州古城、特呈岛", "type": "海滨度假"},
    "茂名": {"province": "广东", "highlights": "放鸡岛、浪漫海岸", "type": "海滨度假"},
    "肇庆": {"province": "广东", "highlights": "七星岩、鼎湖山", "type": "自然风光"},
    "惠州": {"province": "广东", "highlights": "西湖、巽寮湾", "type": "海滨度假"},
    "梅州": {"province": "广东", "highlights": "雁南飞、客天下", "type": "历史文化"},
    "汕尾": {"province": "广东", "highlights": "红海湾、玄武山", "type": "海滨度假"},
    "河源": {"province": "广东", "highlights": "万绿湖、镜花缘", "type": "自然风光"},
    "阳江": {"province": "广东", "highlights": "海陵岛、大角湾", "type": "海滨度假"},
    "清远": {"province": "广东", "highlights": "古龙峡、连州地下河", "type": "自然风光"},
    "东莞": {"province": "广东", "highlights": "可园、松山湖", "type": "历史文化"},
    "中山": {"province": "广东", "highlights": "孙中山故居、影视城", "type": "历史文化"},
    "潮州": {"province": "广东", "highlights": "广济桥、牌坊街", "type": "历史文化"},
    "揭阳": {"province": "广东", "highlights": "进贤门、揭阳楼", "type": "历史文化"},
    "云浮": {"province": "广东", "highlights": "六祖故里、大云雾山", "type": "历史文化"},
    
    # 广西壮族自治区
    "南宁": {"province": "广西", "highlights": "青秀山、大明山", "type": "自然风光"},
    "柳州": {"province": "广西", "highlights": "柳江、大龙潭", "type": "自然风光"},
    "桂林": {"province": "广西", "highlights": "漓江、阳朔、龙脊梯田", "type": "自然风光"},
    "梧州": {"province": "广西", "highlights": "骑楼城", "type": "历史文化"},
    "北海": {"province": "广西", "highlights": "银滩、涠洲岛", "type": "海滨度假"},
    "防城港": {"province": "广西", "highlights": "白浪滩、东兴", "type": "边境旅游"},
    "钦州": {"province": "广西", "highlights": "三娘湾、刘永福故居", "type": "海滨度假"},
    "贵港": {"province": "广西", "highlights": "桂平西山", "type": "自然风光"},
    "玉林": {"province": "广西", "highlights": "大容山、玉林温泉", "type": "自然风光"},
    "百色": {"province": "广西", "highlights": "通灵大峡谷、德天瀑布", "type": "自然风光"},
    "贺州": {"province": "广西", "highlights": "黄姚古镇、姑婆山", "type": "历史文化"},
    "河池": {"province": "广西", "highlights": "巴马长寿村、三门海", "type": "自然风光"},
    "来宾": {"province": "广西", "highlights": "圣堂山", "type": "自然风光"},
    "崇左": {"province": "广西", "highlights": "德天瀑布、明仕田园", "type": "边境旅游"},
    
    # 海南省
    "海口": {"province": "海南", "highlights": "骑楼老街、火山口", "type": "海滨度假"},
    "三亚": {"province": "海南", "highlights": "亚龙湾、蜈支洲岛、天涯海角", "type": "海滨度假"},
    "三沙": {"province": "海南", "highlights": "永兴岛", "type": "海滨度假"},
    "儋州": {"province": "海南", "highlights": "东坡书院、石花水洞", "type": "历史文化"},
    
    # 重庆市
    "重庆": {"province": "重庆", "highlights": "洪崖洞、解放碑、武隆", "type": "历史文化"},
    "万县": {"province": "重庆", "highlights": "三峡", "type": "自然风光"},
    
    # 四川省
    "成都": {"province": "四川", "highlights": "宽窄巷子、大熊猫基地、都江堰", "type": "历史文化"},
    "自贡": {"province": "四川", "highlights": "灯会、恐龙博物馆", "type": "文化体验"},
    "攀枝花": {"province": "四川", "highlights": "二滩国家森林公园", "type": "自然风光"},
    "泸州": {"province": "四川", "highlights": "泸州老窖景区、黄荆老林", "type": "历史文化"},
    "德阳": {"province": "四川", "highlights": "三星堆、孔庙", "type": "历史文化"},
    "绵阳": {"province": "四川", "highlights": "罗浮山、九皇山", "type": "自然风光"},
    "广元": {"province": "四川", "highlights": "剑门关、昭化古城", "type": "历史文化"},
    "遂宁": {"province": "四川", "highlights": "观音湖、广德寺", "type": "自然风光"},
    "内江": {"province": "四川", "highlights": "大千园", "type": "历史文化"},
    "乐山": {"province": "四川", "highlights": "乐山大佛、峨眉山", "type": "历史文化"},
    "南充": {"province": "四川", "highlights": "阆中古城、朱德故居", "type": "历史文化"},
    "眉山": {"province": "四川", "highlights": "三苏祠、瓦屋山", "type": "历史文化"},
    "宜宾": {"province": "四川", "highlights": "蜀南竹海、兴文石海", "type": "自然风光"},
    "广安": {"province": "四川", "highlights": "邓小平故居、华蓥山", "type": "红色旅游"},
    "达州": {"province": "四川", "highlights": "八台山", "type": "自然风光"},
    "雅安": {"province": "四川", "highlights": "牛背山、碧峰峡", "type": "自然风光"},
    "巴中": {"province": "四川", "highlights": "光雾山、诺水河", "type": "自然风光"},
    "资阳": {"province": "四川", "highlights": "安岳石刻", "type": "历史文化"},
    "阿坝": {"province": "四川", "highlights": "九寨沟、黄龙、四姑娘山", "type": "自然风光"},
    "甘孜": {"province": "四川", "highlights": "稻城亚丁、贡嘎山", "type": "自然风光"},
    "凉山": {"province": "四川", "highlights": "泸沽湖、邛海", "type": "自然风光"},
    
    # 贵州省
    "贵阳": {"province": "贵州", "highlights": "甲秀楼、黔灵山", "type": "自然风光"},
    "六盘水": {"province": "贵州", "highlights": "乌蒙大草原、哒啦仙谷", "type": "自然风光"},
    "遵义": {"province": "贵州", "highlights": "遵义会议会址、赤水", "type": "红色旅游"},
    "安顺": {"province": "贵州", "highlights": "黄果树瀑布、龙宫", "type": "自然风光"},
    "毕节": {"province": "贵州", "highlights": "百里杜鹃、织金洞", "type": "自然风光"},
    "铜仁": {"province": "贵州", "highlights": "梵净山、苗王城", "type": "自然风光"},
    "黔西南": {"province": "贵州", "highlights": "马岭河峡谷、万峰林", "type": "自然风光"},
    "黔东南": {"province": "贵州", "highlights": "西江千户苗寨、镇远古镇", "type": "历史文化"},
    "黔南": {"province": "贵州", "highlights": "荔波小七孔、樟江", "type": "自然风光"},
    
    # 云南省
    "昆明": {"province": "云南", "highlights": "滇池、翠湖、石林", "type": "自然风光"},
    "曲靖": {"province": "云南", "highlights": "九龙瀑布、罗平油菜花", "type": "自然风光"},
    "玉溪": {"province": "云南", "highlights": "抚仙湖、聂耳故居", "type": "自然风光"},
    "保山": {"province": "云南", "highlights": "腾冲火山、和顺古镇", "type": "自然风光"},
    "昭通": {"province": "云南", "highlights": "大山包、昭通古城", "type": "自然风光"},
    "丽江": {"province": "云南", "highlights": "丽江古城、玉龙雪山、泸沽湖", "type": "历史文化"},
    "普洱": {"province": "云南", "highlights": "普洱茶马古道", "type": "文化体验"},
    "临沧": {"province": "云南", "highlights": "翁丁佤寨", "type": "自然风光"},
    "楚雄": {"province": "云南", "highlights": "元谋人遗址、楚雄古城", "type": "历史文化"},
    "红河": {"province": "云南", "highlights": "元阳梯田、建水古城", "type": "自然风光"},
    "文山": {"province": "云南", "highlights": "普者黑", "type": "自然风光"},
    "西双版纳": {"province": "云南", "highlights": "热带植物园、野象谷", "type": "自然风光"},
    "大理": {"province": "云南", "highlights": "大理古城、洱海、苍山", "type": "历史文化"},
    "德宏": {"province": "云南", "highlights": "瑞丽、畹町", "type": "边境旅游"},
    "怒江": {"province": "云南", "highlights": "怒江大峡谷", "type": "自然风光"},
    "迪庆": {"province": "云南", "highlights": "香格里拉、普达措", "type": "自然风光"},
    
    # 西藏自治区
    "拉萨": {"province": "西藏", "highlights": "布达拉宫、大昭寺、纳木错", "type": "宗教文化"},
    "日喀则": {"province": "西藏", "highlights": "扎什伦布寺、珠峰大本营", "type": "自然风光"},
    "昌都": {"province": "西藏", "highlights": "然乌湖、来古冰川", "type": "自然风光"},
    "林芝": {"province": "西藏", "highlights": "雅鲁藏布江、巴松措", "type": "自然风光"},
    "山南": {"province": "西藏", "highlights": "羊卓雍措、雍布拉康", "type": "宗教文化"},
    "那曲": {"province": "西藏", "highlights": "可可西里、羌塘草原", "type": "自然风光"},
    "阿里": {"province": "西藏", "highlights": "冈仁波齐、玛旁雍错", "type": "宗教文化"},
    
    # 陕西省
    "西安": {"province": "陕西", "highlights": "兵马俑、古城墙、大雁塔", "type": "历史文化"},
    "铜川": {"province": "陕西", "highlights": "照金牧场、药王山", "type": "自然风光"},
    "宝鸡": {"province": "陕西", "highlights": "法门寺、太白山", "type": "历史文化"},
    "咸阳": {"province": "陕西", "highlights": "乾陵、茂陵", "type": "历史文化"},
    "渭南": {"province": "陕西", "highlights": "华山、司马迁祠", "type": "自然风光"},
    "延安": {"province": "陕西", "highlights": "延安革命纪念馆、壶口瀑布", "type": "红色旅游"},
    "汉中": {"province": "陕西", "highlights": "汉中古城、武侯祠", "type": "历史文化"},
    "榆林": {"province": "陕西", "highlights": "镇北台、红石峡", "type": "历史文化"},
    "安康": {"province": "陕西", "highlights": "瀛湖、南宫山", "type": "自然风光"},
    "商洛": {"province": "陕西", "highlights": "金丝峡、牛背梁", "type": "自然风光"},
    
    # 甘肃省
    "兰州": {"province": "甘肃", "highlights": "黄河铁桥、白塔山", "type": "历史文化"},
    "嘉峪关": {"province": "甘肃", "highlights": "嘉峪关长城、方特", "type": "历史文化"},
    "金昌": {"province": "甘肃", "highlights": "骊靬古城", "type": "历史文化"},
    "白银": {"province": "甘肃", "highlights": "黄河石林", "type": "自然风光"},
    "天水": {"province": "甘肃", "highlights": "麦积山石窟、伏羲庙", "type": "历史文化"},
    "武威": {"province": "甘肃", "highlights": "雷台、文庙", "type": "历史文化"},
    "张掖": {"province": "甘肃", "highlights": "七彩丹霞、平山湖大峡谷", "type": "自然风光"},
    "平凉": {"province": "甘肃", "highlights": "崆峒山", "type": "宗教文化"},
    "酒泉": {"province": "甘肃", "highlights": "莫高窟、鸣沙山月牙泉", "type": "历史文化"},
    "庆阳": {"province": "甘肃", "highlights": "南梁革命纪念馆", "type": "红色旅游"},
    "定西": {"province": "甘肃", "highlights": "定西古城", "type": "历史文化"},
    "陇南": {"province": "甘肃", "highlights": "官鹅沟、万象洞", "type": "自然风光"},
    "临夏": {"province": "甘肃", "highlights": "炳灵寺石窟", "type": "历史文化"},
    "甘南": {"province": "甘肃", "highlights": "拉卜楞寺、桑科草原", "type": "自然风光"},
    
    # 青海省
    "西宁": {"province": "青海", "highlights": "塔尔寺、东关清真大寺", "type": "宗教文化"},
    "海东": {"province": "青海", "highlights": "互助土族故土园", "type": "历史文化"},
    "海北": {"province": "青海", "highlights": "青海湖、门源花海", "type": "自然风光"},
    "黄南": {"province": "青海", "highlights": "热贡艺术之乡", "type": "文化体验"},
    "海南": {"province": "青海", "highlights": "贵德黄河", "type": "自然风光"},
    "果洛": {"province": "青海", "highlights": "年保玉则", "type": "自然风光"},
    "玉树": {"province": "青海", "highlights": "三江源、文成公主庙", "type": "自然风光"},
    "海西": {"province": "青海", "highlights": "茶卡盐湖、翡翠湖", "type": "自然风光"},
    
    # 宁夏回族自治区
    "银川": {"province": "宁夏", "highlights": "西夏王陵、镇北堡西部影城", "type": "历史文化"},
    "石嘴山": {"province": "宁夏", "highlights": "沙湖", "type": "自然风光"},
    "吴忠": {"province": "宁夏", "highlights": "青铜峡108塔", "type": "历史文化"},
    "固原": {"province": "宁夏", "highlights": "六盘山、须弥山石窟", "type": "自然风光"},
    "中卫": {"province": "宁夏", "highlights": "沙坡头、高庙", "type": "自然风光"},
    
    # 新疆维吾尔自治区
    "乌鲁木齐": {"province": "新疆", "highlights": "天山天池、国际大巴扎", "type": "自然风光"},
    "克拉玛依": {"province": "新疆", "highlights": "魔鬼城、黑油山", "type": "自然风光"},
    "吐鲁番": {"province": "新疆", "highlights": "火焰山、葡萄沟、坎儿井", "type": "历史文化"},
    "哈密": {"province": "新疆", "highlights": "巴里坤草原、天山", "type": "自然风光"},
    "昌吉": {"province": "新疆", "highlights": "江布拉克、胡家庄园", "type": "自然风光"},
    "博尔塔拉": {"province": "新疆", "highlights": "赛里木湖", "type": "自然风光"},
    "巴音郭楞": {"province": "新疆", "highlights": "巴音布鲁克、博斯腾湖", "type": "自然风光"},
    "阿克苏": {"province": "新疆", "highlights": "天山大峡谷、阿克苏古城", "type": "自然风光"},
    "克孜勒苏": {"province": "新疆", "highlights": "喀拉库勒湖", "type": "自然风光"},
    "喀什": {"province": "新疆", "highlights": "喀什老城、帕米尔高原", "type": "历史文化"},
    "和田": {"province": "新疆", "highlights": "和田老城、玉龙喀什河", "type": "历史文化"},
    "伊犁": {"province": "新疆", "highlights": "那拉提草原、赛里木湖", "type": "自然风光"},
    "塔城": {"province": "新疆", "highlights": "塔城红楼", "type": "历史文化"},
    "阿勒泰": {"province": "新疆", "highlights": "喀纳斯、禾木", "type": "自然风光"},
    
    # 内蒙古自治区
    "呼和浩特": {"province": "内蒙古", "highlights": "昭君墓、大召寺", "type": "历史文化"},
    "包头": {"province": "内蒙古", "highlights": "响沙湾、包头古城", "type": "自然风光"},
    "乌海": {"province": "内蒙古", "highlights": "乌海湖", "type": "自然风光"},
    "赤峰": {"province": "内蒙古", "highlights": "草原石林、达里湖", "type": "自然风光"},
    "通辽": {"province": "内蒙古", "highlights": "大青沟、珠日河草原", "type": "自然风光"},
    "鄂尔多斯": {"province": "内蒙古", "highlights": "响沙湾、成吉思汗陵", "type": "历史文化"},
    "呼伦贝尔": {"province": "内蒙古", "highlights": "呼伦湖、额尔古纳湿地", "type": "自然风光"},
    "巴彦淖尔": {"province": "内蒙古", "highlights": "乌梁素海", "type": "自然风光"},
    "乌兰察布": {"province": "内蒙古", "highlights": "辉腾锡勒草原", "type": "自然风光"},
    "兴安盟": {"province": "内蒙古", "highlights": "阿尔山", "type": "自然风光"},
    "锡林郭勒": {"province": "内蒙古", "highlights": "锡林郭勒草原、贝子庙", "type": "自然风光"},
    "阿拉善": {"province": "内蒙古", "highlights": "胡杨林、腾格里沙漠", "type": "自然风光"},
}

# 热门/旅游城市（这些城市的景点可以超过15个）
POPULAR_CITIES = {
    "北京", "上海", "广州", "深圳", "杭州", "成都", "重庆",
    "西安", "厦门", "青岛", "三亚", "桂林", "丽江", "大理",
    "昆明", "拉萨", "乌鲁木齐", "哈尔滨", "沈阳", "大连",
    "南京", "苏州", "无锡", "常州", "长沙", "武汉", "郑州",
    "洛阳", "开封", "南京", "绍兴", "福州", "泉州", "黄山",
    "张家界", "九寨沟", "香格里拉", "三亚", "香港", "澳门", "台北",
    "天津", "苏州", "宁波", "温州", "金华", "台州", "嘉兴",
    "绍兴", "湖州", "金华", "衢州", "舟山", "台州", "丽水",
}
